
message(VERBOSE "setting ${PROJECT_NAME} install to ${INSTALL_DIR}/lib/${PROJECT_NAME}")
install(TARGETS ${PROJECT_NAME}
    ARCHIVE DESTINATION ${INSTALL_DIR}/lib/${PROJECT_NAME}
    OPTIONAL
    LIBRARY DESTINATION ${INSTALL_DIR}/lib/${PROJECT_NAME}
    OPTIONAL
)

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include
    OPTIONAL
    DESTINATION ${INSTALL_DIR}/lib/${PROJECT_NAME}
    FILES_MATCHING PATTERN "*.h*"
)
